// commands/asmaulhusna.js
module.exports = {
  name: "asmaulhusna",
  description: "📿 Get a random name from Asmaul Husna (99 names of Allah)",
  category: "islamic",
  async execute(sock, msg, args) {
    const jid = msg.key.remoteJid;

    // Send loading message
    await sock.sendMessage(jid, {
      text: "🔎 Fetching a blessed name from *Asmaul Husna*...",
      forwardingScore: 100,
      isForwarded: true,
    });

    const names = [
      "الرَّحْمَنُ – Ar-Rahman – The Beneficent",
      "الرَّحِيمُ – Ar-Rahim – The Merciful",
      "الْمَلِكُ – Al-Malik – The King and Owner of Dominion",
      "الْقُدُّوسُ – Al-Quddus – The Absolutely Pure",
      "السَّلَامُ – As-Salam – The Source of Peace, Safety",
      "الْمُؤْمِنُ – Al-Mu’min – The Giver of Faith and Security",
      "الْمُهَيْمِنُ – Al-Muhaymin – The Guardian, The Witness",
      "الْعَزِيزُ – Al-Aziz – The Almighty",
      "الْجَبَّارُ – Al-Jabbar – The Compeller, The Restorer",
      "الْمُتَكَبِّرُ – Al-Mutakabbir – The Supreme, The Majestic",
      "الْخَالِقُ – Al-Khaliq – The Creator, The Maker",
      "الْبَارِئُ – Al-Bari – The Evolver",
      "الْمُصَوِّرُ – Al-Musawwir – The Fashioner",
      "الْغَفَّارُ – Al-Ghaffar – The Constant Forgiver",
      "الْقَهَّارُ – Al-Qahhar – The All-Subduer",
      "الْوَهَّابُ – Al-Wahhab – The Supreme Bestower",
      "الرَّزَّاقُ – Ar-Razzaq – The Provider",
      "الْفَتَّاحُ – Al-Fattah – The Supreme Opener",
      "اَلْعَلِيْمُ – Al-`Aleem – The All-Knowing",
      "الْقَابِضُ – Al-Qaabid – The Withholder",
      "الْبَاسِطُ – Al-Baasit – The Extender",
      "الْخَافِضُ – Al-Khaafid – The Reducer",
      "الرَّافِعُ – Ar-Raafi’ – The Exalter, the Elevator",
      "الْمُعِزُّ – Al-Mu’izz – The Honourer, the Bestower",
      "المُذِلُ – Al-Mudhill – The Dishonourer",
      "السَّمِيعُ – As-Samee’ – The All-Hearing",
      "الْبَصِيرُ – Al-Baseer – The All-Seeing",
      "الْحَكَمُ – Al-Hakam – The Impartial Judge",
      "الْعَدْلُ – Al-`Adl – The Utterly Just",
      "اللَّطِيفُ – Al-Lateef – The Subtle One, The Most Gentle",
      "الْخَبِيرُ – Al-Khabeer – The All-Aware",
      "الْحَلِيمُ – Al-Haleem – The Most Forbearing",
      "الْعَظِيمُ – Al-`Azeem – The Magnificent, the Infinite",
      "الْغَفُور – Al-Ghafoor – The Great Forgiver",
      "الشَّكُورُ – Ash-Shakoor – The Most Appreciative",
      "الْعَلِيُ – Al-`Aliyy – The Most High, the Exalted",
      "الْكَبِيرُ – Al-Kabeer – The Most Great",
      "الْحَفِيظُ – Al-Hafeedh – The Preserver",
      "المُقيِت – Al-Muqeet – The Sustainer",
      "اﻟْْحسِيبُ – Al-Haseeb – The Reckoner",
      "الْجَلِيلُ – Al-Jaleel – The Majestic",
      "الْكَرِيمُ – Al-Kareem – The Most Generous, the Most Esteemed",
      "الرَّقِيبُ – Ar-Raqeeb – The Watchful",
      "الْمُجِيبُ – Al-Mujeeb – The Responsive One",
      "الْوَاسِعُ – Al-Waasi’ – The All-Encompassing, the Boundless",
      "الْحَكِيمُ – Al-Hakeem – The All-Wise",
      "الْوَدُودُ – Al-Wadud – The Most Loving",
      "الْمَجِيدُ – Al-Majeed – The Glorious, the Most Honorable",
      "الْبَاعِثُ – Al-Ba’ith – The Infuser of New Life",
      "الشَّهِيدُ – Ash-Shaheed – The All-and-Ever Witnessing",
      "الْحَقُ – Al-Haqq – The Absolute Truth",
      "الْوَكِيلُ – Al-Wakeel – The Trustee, the Disposer of Affairs",
      "الْقَوِي – Al-Qawee – The All-Strong",
      "الْمَتِينُ – Al-Mateen – The Firm One",
      "الْوَلِيُ – Al-Waliyy – The Sole Provider",
      "الْحَمِيدُ – Al-Hameed – The Praiseworthy",
      "الْمُحْصِي – Al-Muhsi – The All-Enumerating, the Counter",
      "الْمُبْدِئُ – Al-Mubdi – The Originator, the Initiator",
      "الْمُعِيدُ – Al-Mueed – The Restorer, the Reinstater",
      "الْمُحْيِي – Al-Muhyi – The Giver of Life",
      "اَلْمُمِيتُ – Al-Mumeet – The Creator of Death",
      "الْحَيُّ – Al-Hayy – The Ever-Living",
      "الْقَيُّومُ – Al-Qayyoom – The Sustainer, The Self-Subsisting",
      "الْوَاجِدُ – Al-Waajid – The Perceiver",
      "الْمَاجِدُ – Al-Maajid – The Glorious, the Most Honorable",
      "الواحِدُ – Al-Waahid – The Only One",
      "اَلاَحَدُ – Al-Ahad – The Indivisible, the Absolute",
      "الصَّمَدُ – As-Samad – The Self-Sufficient, the Impregnable",
      "الْقَادِرُ – Al-Qaadir – The Omnipotent",
      "الْمُقْتَدِرُ – Al-Muqtadir – The Creator of All Power",
      "الْمُقَدِّمُ – Al-Muqaddim – The Expediter",
      "الْمُؤَخِّرُ – Al-Mu’akhkhir – The Delayer",
      "الأوَّلُ – Al-Awwal – The First",
      "الآخِرُ – Al-Akhir – The Last",
      "الظَّاهِرُ – Az-Zaahir – The Manifest",
      "الْبَاطِنُ – Al-Baatin – The Hidden One, Knower of the Hidden",
      "الْوَالِي – Al-Waali – The Sole Governor",
      "الْمُتَعَالِي – Al-Muta’ali – The Self Exalted",
      "الْبَرُّ – Al-Barr – The Source of All Goodness",
      "التَّوَابُ – At-Tawwaab – The Ever-Accepter of Repentance",
      "الْمُنْتَقِمُ – Al-Muntaqim – The Avenger",
      "العَفُو – Al-‘Afuww – The Supreme Pardoner",
      "الرَّؤُوفُ – Ar-Ra’oof – The Most Kind",
      "مَالِكُ الْمُلْكِ – Maalik-ul-Mulk – Master and King of the Kingdom",
      "ذُوالْجَلاَلِ وَالإكْرَامِ – Dhul-Jalaali Wal-Ikraam – Lord of Glory and Honour, Lord of Majesty and Generosity",
      "الْمُقْسِطُ – Al-Muqsit – The Just One",
      "الْجَامِعُ – Al-Jaami’ – The Gatherer, the Uniter",
      "ٱلْغَنيُ – Al-Ghaniyy – The Self-Sufficient, the Wealthy",
      "ٱلْمُغْنِيُ – Al-Mughni – The Enricher",
      "اَلْمَانِعُ – Al-Maani’ – The Withholder",
      "الضَّارَ – Ad-Daarr – Distresser",
      "النَّافِعُ – An-Naafi’ – The Propitious, the Benefactor",
      "النُّورُ – An-Noor – The Light, the Illuminator",
      "الْهَادِي – Al-Haadi – The Guide",
      "الْبَدِيعُ – Al-Badee’ – The Incomparable Originator",
      "البَاقِي – Al-Baaqi – The Everlasting",
      "الْوَارِثُ – Al-Waarith – The Inheritor, the Heir",
      "الرَّشِيدُ – Ar-Rasheed – The Guide, Infallible Teacher, and Knower",
      "الصَّبُورُ – As-Saboor – The Most Patient"
    ];

    const randomName = names[Math.floor(Math.random() * names.length)];

    await sock.sendMessage(jid, {
      text: `🕋 *One of the 99 Names of Allah*\n\n✨ ${randomName}`,
      footer: "Ben Whittaker Tech • Asmaul Husna",
      forwardingScore: 999,
      isForwarded: true,
    });
  }
};
